name: codex

services:
  devcontainer: &base
    image: codex-linux-dev
    build:
      context: ./codex/.devcontainer
    tty: true
    stdin_open: true
    privileged: true
    environment: &env_base
      TZ: JST

  codex:
    <<: *base
    image: codex-linux
    build:
      context: .
      dockerfile: Dockerfile
#    network_mode: "host"
    environment:
      <<: *env_base
      CARGO_TARGET_DIR: '/workspace/codex-rs/target-amd64'
#      OPENAI_API_KEY: 'sk-proj--__YOUR_API_KEY__'
    volumes:
      - '$PWD/codex:/workspace'
    platform: 'linux/amd64'
    working_dir: '/workspace/codex-rs'

#secrets:
#  ubuntu_pw:
#    file: './ubuntu.passwd'
